### ISSUE TITLE
FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado.

### ISSUE THREAD

**Issue by evandrocoan** [evandrocoan/SublimeStudio#71]
```
plugins loaded
SQLTools (v0.9.6): Logging is active
SQLTools (v0.9.6): Connection timeout set to 15 seconds
SQLTools (v0.9.6): Connection history defined with max size 100
SQLTools (v0.9.6): SQLTools Loaded!
SublimeLinter: debug mode: off 
OverrideAudit: Sublime version is unchanged; skipping automatic report
Loaded LaTeXTools plugins ['base_viewer'] from path L:\SublimeText3143\Data\Packages\LaTeXTools\viewers\base_viewer.py
Loaded LaTeXTools plugins ['command_viewer', 'okular_viewer', 'sumatra_viewer', 'zathura_viewer', 'preview_viewer', 'evince_viewer', 'skim_viewer'] from path L:\SublimeText3143\Data\Packages\LaTeXTools\viewers
Traceback (most recent call last):
  File "L:\SublimeText3143\Data\Installed Packages\amxmodx.sublime-package\watchdog\observers\api.py", line 322, in schedule
    emitter = self._get_emitter_for_watch(watch)
  File "L:\SublimeText3143\Data\Installed Packages\amxmodx.sublime-package\watchdog\observers\api.py", line 265, in _get_emitter_for_watch
    return self._emitter_for_watch[watch]
KeyError: <ObservedWatch: path=F:\SteamCMD\steamapps\common\Half-Life\czero\addons\amxmodx\scripting\include, is_recursive=True>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\SublimeText3143\sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "AMXXEditor in L:\SublimeText3143\Data\Installed Packages\amxmodx.sublime-package", line 54, in plugin_loaded
  File "AMXXEditor in L:\SublimeText3143\Data\Installed Packages\amxmodx.sublime-package", line 662, in on_settings_modified
  File "L:\SublimeText3143\Data\Installed Packages\amxmodx.sublime-package\watchdog\observers\api.py", line 327, in schedule
    timeout=self.timeout)
  File "L:\SublimeText3143\Data\Installed Packages\amxmodx.sublime-package\watchdog\observers\read_directory_changes.py", line 67, in __init__
    self._handle = get_directory_handle(watch.path)
  File "L:\SublimeText3143\Data\Installed Packages\amxmodx.sublime-package\watchdog\observers\winapi.py", line 281, in get_directory_handle
    None, OPEN_EXISTING, WATCHDOG_FILE_FLAGS, None)
  File "L:\SublimeText3143\Data\Installed Packages\amxmodx.sublime-package\watchdog\observers\winapi.py", line 116, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado.
syncScroll starting
Loading LaTeXTools plugins...
Emmet: No need to update PyV8
```

**Comment by evandrocoan** [comment]
Still doing it on the Stable version when the directory does not exists:
```
plugins loaded
Traceback (most recent call last):
  File "L:\Programs\SublimeText\Data\Packages\AmxxEditor\watchdog\observers\api.py", line 322, in schedule
    emitter = self._get_emitter_for_watch(watch)
  File "L:\Programs\SublimeText\Data\Packages\AmxxEditor\watchdog\observers\api.py", line 265, in _get_emitter_for_watch
    return self._emitter_for_watch[watch]
KeyError: <ObservedWatch: path=F:\SteamCMD\steamapps\common\Half-Life\czero\addons\amxmodx\scripting\include, is_recursive=True>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\Programs\SublimeText\sublime_plugin.py", line 283, in on_api_ready
    m.plugin_loaded()
  File "L:\Programs\SublimeText\Data\Packages\AmxxEditor\AmxxEditor.py", line 131, in plugin_loaded
    on_settings_modified();
  File "L:\Programs\SublimeText\Data\Packages\AmxxEditor\AmxxEditor.py", line 627, in on_settings_modified
    file_observer.schedule( file_event_handler, directory, True )
  File "L:\Programs\SublimeText\Data\Packages\AmxxEditor\watchdog\observers\api.py", line 327, in schedule
    timeout=self.timeout)
  File "L:\Programs\SublimeText\Data\Packages\AmxxEditor\watchdog\observers\read_directory_changes.py", line 67, in __init__
    self._handle = get_directory_handle(watch.path)
  File "L:\Programs\SublimeText\Data\Packages\AmxxEditor\watchdog\observers\winapi.py", line 281, in get_directory_handle
    None, OPEN_EXISTING, WATCHDOG_FILE_FLAGS, None)
  File "L:\Programs\SublimeText\Data\Packages\AmxxEditor\watchdog\observers\winapi.py", line 116, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado.
15:05:43:142.208099 1.18e+01 - PlantUmlDiagrams.diagram.load_preprocessor:57 - Loading plantuml_processor class: <class 'PlantUmlDiagrams.diagram.plantuml.PlantUMLProcessor'>
15:05:43:319.937944 1.20e+01 - PlantUmlDiagrams.diagram.plantuml.find_plantuml_jar:249 - Detected C:\Users\plantuml.jar
15:05:43:382.452011 6.81e-02 - PlantUmlDiagrams.diagram.plantuml.check_plantuml_functionality:231 - PlantUMLDiagrams: ERROR, PlantUML does not appear functional: b'Error: Unable to access jarfile C:\\Users\\plantuml.jar\r\n'
```
